version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: digital-rights-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: digital_rights
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 